# Generated by Django 6.1.2 on 2026-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_translated_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Nomi (UZ)'),
        ),
    ]
